services:
  - type: web
    name: hoja-de-vida
    env: python
    plan: free
    region: oregon  # ¡IMPORTANTE! Misma región que tu PostgreSQL
    buildCommand: "./build.sh"
    startCommand: "gunicorn mi_proyecto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://bd_hojacv_user:WEaWUGuFvJVKa7AUfuSKmdpcbkmGxWSM@dpg-d5cq34er433s73a0dfog-a.oregon-postgres.render.com/bd_hojacv
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true