services:
  - type: web
    name: hoja-de-vida
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mi_proyecto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://bd_hojacv_user:WEaWUGuFvJVKa7AUfuSKmdpcbkmGxWSM@dpg-d5cq34er433s73a0dfog-a.oregon-postgres.render.com/bd_hojacv
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.13.3  # Â¡CAMBIADO! De 3.13.3 a 3.11.0
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
    healthCheckPath: /
    autoDeploy: true