services:
  - type: web
    name: hoja-de-vida
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mi_proyecto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hoja_de_vida_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: hoja_de_vida_db
    plan: free