services:
  - type: web
    name: hoja-de-vida
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mi_proyecto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://bd_hojacv_user:WEaWUGuFvJVKa7AUfuSKmdpcbkmGxWSM@dpg-d5cq34er433s73a0dfog-a.oregon-postgres.render.com/bd_hojacv
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true